apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-go-deployment
  namespace: hello-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-go
  template:
    metadata:
      labels:
        app: hello-go
    spec:
      imagePullSecrets:
        - name: nexus-secret
      containers:
      - name: hello-go
        image: 127.0.0.1:30085/my-repository/hello-go:v001
        ports:
        - containerPort: 8099
---
apiVersion: v1
kind: Service
metadata:
  name: hello-go-service
  namespace: hello-go
spec:
  selector:
    app: hello-go
  ports:
    - protocol: TCP
      port: 8099  # Service port
      targetPort: 8099  # Container port
  type: ClusterIP
